# Generated by Django 2.0.13 on 2019-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIdea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analyst', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_bucket', models.CharField(blank=True, choices=[('Catalyst-Driven Credit', 'Catalyst-Driven Credit'), ('Merger Related Credit', 'Merger Related Credit'), ('Relative Value Credit', 'Relative Value Credit'), ('Distressed', 'Distressed'), ('Yield to Call', 'Yield to Call')], max_length=100, null=True)),
                ('deal_strategy_type', models.CharField(blank=True, choices=[('Refinancing', 'Refinancing'), ('Speculated M&A', 'Speculated M&A'), ('Merger Arbitrage', 'Merger Arbitrage'), ('Relative Value', 'Relative Value'), ('Definitive M&A', 'Definitive M&A'), ('Special Situation', 'Special Situation'), ('Levering', 'Levering'), ('Deep Value', 'Deep Value'), ('De-Levering', 'De-Levering'), ('Spin-off', 'Spin-off')], max_length=100, null=True)),
                ('catalyst', models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=100, null=True)),
                ('catalyst_tier', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True)),
                ('target_sec_cusip', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('hedge_sec_cusip', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_closing_date', models.DateField(blank=True, null=True)),
                ('upside_price', models.FloatField(blank=True, null=True)),
                ('downside_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
