# Generated by Django 2.0.10 on 2019-07-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditidea',
            name='arb_tradegroup',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
