# Generated by Django 2.0.13 on 2019-07-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0003_creditideadetails_creditideascenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIdeaCreditDetails',
            fields=[
                ('credit_idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='credit_idea.CreditIdea')),
                ('bond_ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('face_value_of_bonds', models.FloatField(blank=True, null=True)),
                ('bbg_security_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bbg_interest_rate', models.FloatField(blank=True, null=True)),
                ('bbg_issue_size', models.FloatField(blank=True, null=True)),
                ('bond_est_purchase_price', models.FloatField(blank=True, null=True)),
                ('bbg_bid_price', models.FloatField(blank=True, null=True)),
                ('bbg_ask_price', models.FloatField(blank=True, null=True)),
                ('bbg_last_price', models.FloatField(blank=True, null=True)),
                ('base_break_price', models.FloatField(blank=True, null=True)),
                ('conservative_break_price', models.FloatField(blank=True, null=True)),
                ('call_price', models.FloatField(blank=True, null=True)),
                ('make_whole_price', models.FloatField(blank=True, null=True)),
                ('equity_claw_percent', models.FloatField(blank=True, null=True)),
                ('equity_claw_value', models.FloatField(blank=True, null=True)),
                ('blend', models.FloatField(blank=True, null=True)),
                ('change_of_control', models.FloatField(blank=True, null=True)),
                ('acq_credit', models.FloatField(blank=True, null=True)),
                ('proposed_ratio', models.FloatField(blank=True, null=True)),
                ('bbg_est_daily_vol', models.FloatField(blank=True, null=True)),
                ('bbg_actual_thirty_day', models.FloatField(blank=True, null=True)),
                ('credit_team_view', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditIdeaCreditScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(blank=True, max_length=50, null=True)),
                ('is_hedge', models.BooleanField()),
                ('bond_last_price', models.FloatField(blank=True, default=0, null=True)),
                ('bond_redemption', models.FloatField(blank=True, default=0, null=True)),
                ('bond_carry_earned', models.FloatField(blank=True, default=0, null=True)),
                ('bond_rebate', models.FloatField(blank=True, default=0, null=True)),
                ('bond_hedge', models.FloatField(blank=True, default=0, null=True)),
                ('bond_deal_value', models.FloatField(blank=True, default=0, null=True)),
                ('bond_spread', models.FloatField(blank=True, default=0, null=True)),
                ('returns_gross_pct', models.FloatField(blank=True, default=0, null=True)),
                ('returns_annual_pct', models.FloatField(blank=True, default=0, null=True)),
                ('returns_estimated_closing_date', models.DateField(blank=True, null=True)),
                ('returns_days_to_close', models.IntegerField(blank=True, default=0, null=True)),
                ('profits_principal', models.FloatField(blank=True, default=0, null=True)),
                ('profits_carry', models.FloatField(blank=True, default=0, null=True)),
                ('profits_rebate', models.FloatField(blank=True, default=0, null=True)),
                ('profits_hedge', models.FloatField(blank=True, default=0, null=True)),
                ('profits_total', models.FloatField(blank=True, default=0, null=True)),
                ('profits_day_of_break', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_idea.CreditIdea')),
            ],
        ),
    ]
