# Generated by Django 2.0.13 on 2019-07-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0006_creditideacreditdetails_break_spread'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIdeaCreditScenarioComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_idea.CreditIdea')),
            ],
        ),
    ]
