# Generated by Django 2.0.13 on 2019-08-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0007_creditideacreditscenariocomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditideacreditdetails',
            name='other_acq_credit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
