# Generated by Django 2.0.13 on 2019-08-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0008_creditideacreditdetails_other_acq_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditidea',
            name='other_tradegroup',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
