# Generated by Django 2.0.13 on 2019-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0009_creditidea_other_tradegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditideacreditscenario',
            name='bond_redemption_type',
            field=models.TextField(blank=True, default='Base Break Price', null=True),
        ),
    ]
