# Generated by Django 2.0.10 on 2019-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0010_creditideacreditscenario_bond_redemption_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditidea',
            name='deal_category',
            field=models.CharField(blank=True, choices=[('Actionable', 'Actionable'), ('Not Actionable', 'Not Actionable'), ('Bank Debt', 'Bank Debt'), ('Convertible Only', 'Convertible Only'), ('No Credit', 'No Credit')], max_length=100, null=True),
        ),
    ]
