# Generated by Django 2.0.13 on 2019-08-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0011_creditidea_deal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIdeaComments',
            fields=[
                ('credit_idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='credit_idea.CreditIdea')),
                ('summary_comments', models.TextField(blank=True, default='', null=True)),
                ('press_release_comments', models.TextField(blank=True, default='', null=True)),
                ('proxy_statement_comments', models.TextField(blank=True, default='', null=True)),
                ('change_of_control_comments', models.TextField(blank=True, default='', null=True)),
                ('restricted_payments_comments', models.TextField(blank=True, default='', null=True)),
                ('liens_indebtedness_comments', models.TextField(blank=True, default='', null=True)),
                ('other_comments', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
