# Generated by Django 2.0.13 on 2019-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0012_creditideacomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditidea',
            name='deal_category',
            field=models.CharField(blank=True, choices=[('Actionable', 'Actionable'), ('Not Actionable', 'Not Actionable'), ('Bank Debt', 'Bank Debt'), ('Convertible Only', 'Convertible Only'), ('No Credit', 'No Credit'), ('Archive', 'Archive')], max_length=100, null=True),
        ),
    ]
