# Generated by Django 2.0.13 on 2023-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0014_creditstaticscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstaticscreen',
            name='cr01',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='creditstaticscreen',
            name='dv01',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
