# Generated by Django 2.0.13 on 2023-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0015_auto_20230905_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='dte',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='eff_duration',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='return_1_yr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='return_3_yr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='return_5_yr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='return_5d',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='return_mtd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='return_ytd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='ytc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='yte',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='ytm',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='ytw',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
    ]
