# Generated by Django 2.0.13 on 2023-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0017_creditstaticscreen_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='cr01',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='dv01',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
