# Generated by Django 2.0.13 on 2023-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_idea', '0020_auto_20230915_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstaticscreen',
            name='ytc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
