from django.conf.urls import url
from . import views

app_name = 'portfolio_optimization'

urlpatterns = [
    url('ess_target_configs$', views.EssDealTypeParametersView.as_view(), name='ess_target_configs'),
    url('update_normlized_sizing_by_risk_adj_prob$', views.update_normlized_sizing_by_risk_adj_prob,
        name='update_normlized_sizing_by_risk_adj_prob'),
    url('update_soft_catalyst_risk_sizing$', views.update_soft_catalyst_risk_sizing,
        name='update_soft_catalyst_risk_sizing'),
    url('ess_potential_long_shorts', views.EssLongShortView.as_view(), name='ess_potential_long_shorts'),
    url('ess_implied_probabilites$', views.EssImpliedProbabilityView.as_view(),
        name='ess_implied_probabilites'),
    url('ess_implied_prob_drilldown$', views.ess_implied_prob_drilldown,
        name='ess_implied_prob_drilldown'),
    url('get_deal_type_details/', views.get_deal_type_details, name='get_deal_type_details'),
    url('delete_deal_type/', views.delete_deal_type, name='delete_deal_type'),
    url('wic_universe_rors', views.WicUniverseRorView.as_view(), name='wic_universe_rors'),
    url('arb_hard_optimization$', views.ArbHardOptimizationView.as_view(), name='arb_hard_optimization'),
    url('credit_hard_optimization$', views.CreditHardOptimizationView.as_view(), name='credit_hard_optimization'),
    url('pnl_potential$', views.PnlPotentialView.as_view(), name='pnl_potential'),
    url('save_pnl_potential_new_date$', views.save_pnl_potential_new_date, name='save_pnl_potential_new_date'),
    url('save_pnl_potential_exclusion_deal$', views.save_pnl_potential_exclusion_deal, name='save_pnl_potential_exclusion_deal'),
    url('get_aed_sleeve_perf_view$', views.get_aed_sleeve_perf_view, name='get_aed_sleeve_perf_view'),
    url('get_deal_names$', views.get_deal_names, name='get_deal_names'),
    url('save_pnl_potential_scenario$', views.save_pnl_potential_scenario, name='save_pnl_potential_scenario'),
    url('save_required_return$', views.save_required_return, name='save_required_return'),
    url('save_pnl_potential_ess_scenario$', views.save_pnl_potential_ess_scenario, name='save_pnl_potential_ess_scenario'),
    url('save_pnl_potential_credit_arb_scenario$', views.save_pnl_potential_credit_arb_scenario, name='save_pnl_potential_credit_arb_scenario'),
    url('update_pnl_potential_scenario$', views.update_pnl_potential_scenario, name='update_pnl_potential_scenario'),
    url('save_pnl_potential_incremental$', views.save_pnl_potential_incremental, name='save_pnl_potential_incremental'),
    url('update_pnl_potential_incremental$', views.update_pnl_potential_incremental, name='update_pnl_potential_incremental'),
    url('delete_pnl_potential_row$', views.delete_pnl_potential_row, name='delete_pnl_potential_row'),
    url('get_scenario_detail$', views.get_scenario_detail, name='get_scenario_detail'),
    url('delete_scenario$', views.delete_scenario, name='delete_scenario'),
    url('get_pnl_potential_scenarios$', views.get_pnl_potential_scenarios, name='get_pnl_potential_scenarios'),
    url('get_incremental_detail$', views.get_incremental_detail, name='get_incremental_detail'),
    url('save_hard_opt_comment$', views.save_hard_opt_comment, name='save_hard_opt_comment'),
    url('save_rebal_paramaters$', views.save_rebal_paramaters, name='save_rebal_paramaters'),
    url('save_exclusion_hard_opt$', views.save_exclusion_hard_opt, name='save_exclusion_hard_opt'),
    url('rebalance_portfolio$', views.rebalance_portfolio, name='rebalance_portfolio'),
    url('download_hard_opt_data$', views.download_hard_opt_data, name='download_hard_opt_data'),
    url('download_credit_hard_opt_data$', views.download_credit_hard_opt_data, name='download_credit_hard_opt_data'),
    url('update_pnl_ess_constituents_view$', views.update_pnl_ess_constituents_view, name='update_pnl_ess_constituents_view'),
]
