# Generated by Django 2.0.10 on 2020-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtfRecRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sedol', models.CharField(max_length=20)),
                ('eze_ticker', models.CharField(max_length=25)),
                ('deal', models.CharField(max_length=25)),
                ('index', models.FloatField(null=True)),
                ('eze', models.FloatField(null=True)),
                ('basket', models.FloatField(null=True)),
                ('index_eze', models.FloatField(null=True)),
                ('basket_eze', models.FloatField(null=True)),
                ('index_basket', models.FloatField(null=True)),
                ('weight_tracked', models.FloatField(null=True)),
                ('pct_tracked', models.FloatField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtfRecSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index_weights_long', models.FloatField(null=True)),
                ('index_weights_short', models.FloatField(null=True)),
                ('index_weights_gross', models.FloatField(null=True)),
                ('weight_tracked_long', models.FloatField(null=True)),
                ('weight_tracked_short', models.FloatField(null=True)),
                ('weight_tracked_gross', models.FloatField(null=True)),
                ('pct_tracked_long', models.FloatField(null=True)),
                ('pct_tracked_short', models.FloatField(null=True)),
                ('pct_tracked_gross', models.FloatField(null=True)),
            ],
        ),
    ]
