# Generated by Django 2.0.10 on 2020-09-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField()),
                ('collateral_buffer', models.FloatField(default=0)),
                ('net_td_creations', models.IntegerField(default=0)),
                ('net_td_redemptions', models.IntegerField(default=0)),
            ],
        ),
    ]
