# Generated by Django 2.0.10 on 2020-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0002_customuserinputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFLivePnL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('cur', models.CharField(max_length=5, null=True)),
                ('sedol', models.CharField(max_length=12, null=True)),
                ('basket_unit_size', models.FloatField(null=True)),
                ('base_mv', models.FloatField(null=True)),
                ('local_price', models.FloatField(null=True)),
                ('base_price', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('cil', models.CharField(max_length=2, null=True)),
                ('tradegroup', models.CharField(max_length=30, null=True)),
                ('eze_ticker', models.CharField(max_length=10, null=True)),
                ('eze_shares', models.FloatField(null=True)),
                ('pct_nav_cu', models.FloatField(null=True)),
                ('live_price', models.FloatField(null=True)),
                ('px_change', models.FloatField(null=True)),
                ('stock_return', models.FloatField(null=True)),
                ('deal_return', models.FloatField(null=True)),
                ('one_day_return', models.FloatField(null=True)),
                ('five_day_return', models.FloatField(null=True)),
                ('ytd_return', models.FloatField(null=True)),
                ('live_ytd_return', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETFMonitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
                ('spread_monitor', models.TextField(null=True)),
                ('bid_ask_monitor', models.TextField(null=True)),
                ('bid_ask_spread_monitor', models.TextField(null=True)),
                ('nav_monitor', models.TextField(null=True)),
                ('basket_valuation_monitor', models.TextField(null=True)),
            ],
        ),
    ]
