# Generated by Django 2.0.10 on 2020-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0003_etflivepnl_etfmonitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etflivepnl',
            name='eze_ticker',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='etflivepnl',
            name='ticker',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
