# Generated by Django 2.0.10 on 2020-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0006_etfmonitors_unit_activity_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOnClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
                ('cil', models.CharField(max_length=2, null=True)),
                ('sedol', models.CharField(max_length=12, null=True)),
                ('tradegroup', models.CharField(max_length=50, null=True)),
                ('eze_ticker', models.CharField(max_length=25, null=True)),
                ('eze_shares', models.FloatField(null=True)),
                ('trade_size', models.FloatField(null=True)),
                ('side', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
