# Generated by Django 2.0.10 on 2020-10-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0007_marketonclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserinputs',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuserinputs',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='etflivepnl',
            name='ask_market_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etflivepnl',
            name='bid_market_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etflivepnl',
            name='cil_mv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etflivepnl',
            name='usd_live_price',
            field=models.FloatField(null=True),
        ),
    ]
