# Generated by Django 2.0.10 on 2020-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0008_auto_20201001_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfmonitors',
            name='spread_estimate_monitor',
            field=models.TextField(null=True),
        ),
    ]
