# Generated by Django 2.0.10 on 2020-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0009_etfmonitors_spread_estimate_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='etflivepnl',
            name='security_ask',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etflivepnl',
            name='security_bid',
            field=models.FloatField(null=True),
        ),
    ]
