# Generated by Django 2.0.10 on 2020-10-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0010_auto_20201001_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='etflivepnl',
            name='live_fx_price',
            field=models.FloatField(null=True),
        ),
    ]
