# Generated by Django 2.0.10 on 2020-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0011_etflivepnl_live_fx_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketonclose',
            old_name='eze_shares',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='marketonclose',
            old_name='eze_ticker',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='marketonclose',
            old_name='updated_on',
            new_name='tradedate',
        ),
        migrations.RemoveField(
            model_name='marketonclose',
            name='cil',
        ),
        migrations.RemoveField(
            model_name='marketonclose',
            name='sedol',
        ),
        migrations.RemoveField(
            model_name='marketonclose',
            name='trade_size',
        ),
        migrations.RemoveField(
            model_name='marketonclose',
            name='tradegroup',
        ),
        migrations.AddField(
            model_name='marketonclose',
            name='broker',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketonclose',
            name='manager',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketonclose',
            name='prt',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketonclose',
            name='strategy1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marketonclose',
            name='trader',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
