# Generated by Django 2.0.10 on 2020-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0012_auto_20201002_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfrecrecords',
            name='additional_etf_exposure',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='etfrecsummary',
            name='additional_etf_exposure_gross',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etfrecsummary',
            name='additional_etf_exposure_long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etfrecsummary',
            name='additional_etf_exposure_short',
            field=models.FloatField(null=True),
        ),
    ]
