# Generated by Django 2.0.10 on 2020-10-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0013_auto_20201008_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfrecsummary',
            name='additional_etf_exposure_forwards',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etfrecsummary',
            name='index_weights_forwards',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etfrecsummary',
            name='pct_tracked_forwards',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='etfrecsummary',
            name='weight_tracked_forwards',
            field=models.FloatField(null=True),
        ),
    ]
