# Generated by Django 2.0.13 on 2024-03-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0015_etfrecrecords_sectype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIndexPnL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('ticker', models.CharField(max_length=25, null=True)),
                ('cur', models.CharField(max_length=5, null=True)),
                ('sedol', models.CharField(max_length=12, null=True)),
                ('tradegroup', models.CharField(max_length=12, null=True)),
                ('pnl', models.FloatField(null=True)),
                ('Dividend_Pnl', models.FloatField(null=True)),
                ('tradar_pnl', models.FloatField(null=True)),
            ],
        ),
    ]
