# Generated by Django 2.0.13 on 2024-03-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0016_dailyindexpnl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyindexpnl',
            old_name='Dividend_Pnl',
            new_name='dividend_pnl',
        ),
    ]
