# Generated by Django 2.0.13 on 2024-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0018_auto_20240401_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyindexpnl',
            name='closing_hedged_weight',
            field=models.FloatField(null=True),
        ),
    ]
