# Generated by Django 2.0.13 on 2024-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0019_dailyindexpnl_closing_hedged_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyindexpnl',
            name='tradar_pnl',
        ),
        migrations.AddField(
            model_name='dailyindexpnl',
            name='sectype',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
