# Generated by Django 2.0.13 on 2024-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0020_auto_20240425_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyindexpnl',
            name='opening_price',
            field=models.FloatField(null=True),
        ),
    ]
